POST http://localhost:5000/api/signin


###

POST http://localhost:5000/api/signup
content-type: application/json

{
    "firstName":"maicol manuel",
    "lastName":"orosco vasquez",
    "username":"ibearsmile",
    "email":"maicol@gmail.com",
    "password":"12345"
}
###

POST http://localhost:5000/api/activate
content-type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJtYWljb2wgbWFudWVsIiwibGFzdE5hbWUiOiJvcm9zY28gdmFzdXFleiIsInVzZXJuYW1lIjoiaWJlYXJzbWlsZSIsImVtYWlsIjoibWFpY29sQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDUiLCJpYXQiOjE2MjIxMzk4NDYsImV4cCI6MTYyMjE0MDc0Nn0.Jg0NeoncHhxVpKiOCewYLxVKaAVHxG36FFYxNQon6xQ"
}

###

POST http://localhost:5000/api/signin
content-type: application/json

{
    "email":"ibearsmile",
    "password":"12345",
    "connect":true
}